.PHONY: build run test clean proto deps

PROTO_INCLUDE ?= /usr/local/include

build:
	go build -o bin/{{.ProjectName}} .

run:
	go run .

test:
	go test ./...

clean:
	rm -rf bin/

proto:
	protoc proto/*.proto \
		-I . -I $(PROTO_INCLUDE) \
		--go_out=. --go_opt=paths=source_relative \
		--myhttp_out=. --myhttp_opt=paths=source_relative

deps:
	go mod tidy
