syntax = "proto3";

package hollow.example;

option go_package = "github.com/vaynedu/hollow/example/proto";

import "google/api/annotations.proto";

message CreateUserRequest {
  string username = 1;
}

message CreateUserResponse {
  string id = 1;
}

message GetUserRequest {
  string id = 1;
}

message GetUserResponse {
  string id = 1;
}

service UserService {
  rpc CreateUser (CreateUserRequest) returns (CreateUserResponse) {
    option (google.api.http) = {
      post: "/v1/users"
      body: "*"
    };
  }

  rpc GetUser (GetUserRequest) returns (GetUserResponse) {
    option (google.api.http) = {
      get: "/v1/users"
    };
  }
}
