// Code generated by github.com/vaynedu/protoc-gen-myhttp. DO NOT EDIT.
// Code generated by github.com/vaynedu/protoc-gen-myhttp. DO NOT EDIT.
// Code generated by github.com/vaynedu/protoc-gen-myhttp. DO NOT EDIT.

package proto

import (
	"context"
	"fmt"

	"github.com/gin-gonic/gin"
	"github.com/vaynedu/hollow/pkg/hecode"
)

type UserServiceService interface {
	CreateUser(ctx context.Context, req *CreateUserRequest) (resp *CreateUserResponse, err error)
	GetUser(ctx context.Context, req *GetUserRequest) (resp *GetUserResponse, err error)
}

type UserService struct {
	svc UserServiceService
}

func RegisterUserServiceGinRouter(router *gin.Engine, svc UserServiceService) {
	s := UserService{
		svc: svc,
	}

	router.POST("/v1/users", s.CreateUser)

	router.GET("/v1/users", s.GetUser)

}

func (s *UserService) CreateUser(c *gin.Context) {
	var req CreateUserRequest

	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(fmt.Errorf("%w: bind request: %v", hecode.ErrInvalidParam, err))
		return
	}

	resp, err := s.svc.CreateUser(c.Request.Context(), &req)
	if err != nil {
		c.Error(err)
		return
	}
	c.Set("data", resp)
}

func (s *UserService) GetUser(c *gin.Context) {
	var req GetUserRequest

	if err := c.ShouldBindQuery(&req); err != nil {
		c.Error(fmt.Errorf("%w: bind request: %v", hecode.ErrInvalidParam, err))
		return
	}

	resp, err := s.svc.GetUser(c.Request.Context(), &req)
	if err != nil {
		c.Error(err)
		return
	}
	c.Set("data", resp)
}

// 新增未实现的服务结构体
type UnimplementedUserServiceService struct{}

// 为每个方法提供错误实现

func (u *UnimplementedUserServiceService) CreateUser(ctx context.Context, req *CreateUserRequest) (resp *CreateUserResponse, err error) {
	return nil, fmt.Errorf("UserServiceService.CreateUser 方法未实现")
}

func (u *UnimplementedUserServiceService) GetUser(ctx context.Context, req *GetUserRequest) (resp *GetUserResponse, err error) {
	return nil, fmt.Errorf("UserServiceService.GetUser 方法未实现")
}
