// Code generated by github.com/vaynedu/protoc-gen-myhttp. DO NOT EDIT.
// Code generated by github.com/vaynedu/protoc-gen-myhttp. DO NOT EDIT.
// Code generated by github.com/vaynedu/protoc-gen-myhttp. DO NOT EDIT.

package proto

import (
	"context"
	"fmt"
	"github.com/gin-gonic/gin"
)

type HelloServiceService interface {
	SayHello(ctx context.Context, req *HelloRequest) (resp *HelloResponse, err error)
}

type HelloService struct {
	svc HelloServiceService
}

func RegisterHelloServiceGinRouter(router *gin.Engine, svc HelloServiceService) {
	s := HelloService{
		svc: svc,
	}

	router.GET("/v1/hello", s.SayHello)

}

func (s *HelloService) SayHello(c *gin.Context) {
	var req HelloRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(400, gin.H{"error": err.Error()})
		return
	}
	resp, err := s.svc.SayHello(c.Request.Context(), &req)
	if err != nil {
		c.JSON(500, gin.H{"error": err.Error()})
		return
	}
	c.JSON(200, resp)
}

// 新增未实现的服务结构体
type UnimplementedHelloServiceService struct{}

// 为每个方法提供错误实现

func (u *UnimplementedHelloServiceService) SayHello(ctx context.Context, req *HelloRequest) (resp *HelloResponse, err error) {
	return nil, fmt.Errorf("HelloServiceService.SayHello 方法未实现")
}
